import { createTamagui, createTokens } from '@tamagui/core';
import { config as defaultConfig } from '@tamagui/config/v3';

const customColors = {
  primary: '#667eea',
  primaryDark: '#764ba2',
  primaryLight: '#8b5cf6',

  secondary: '#10B981',
  secondaryDark: '#059669',
  secondaryLight: '#34D399',

  accent: '#F59E0B',
  accentDark: '#D97706',
  accentLight: '#FBBF24',

  success: '#059669',
  warning: '#F59E0B',
  error: '#EF4444',
  info: '#3B82F6',

  light: {
    bg: '#f5f7fa',
    card: '#ffffff',
    cardHover: '#f9fafb',
    border: '#e5e7eb',
    borderHover: '#d1d5db',
    text: '#111827',
    textSecondary: '#6b7280',
    textTertiary: '#9ca3af',
  },

  dark: {
    bg: '#111827',
    card: '#1f2937',
    cardHover: '#374151',
    border: '#4b5563',
    borderHover: '#6b7280',
    text: '#f9fafb',
    textSecondary: '#d1d5db',
    textTertiary: '#9ca3af',
  },
};

const customTokens = createTokens({
  color: {
    primary: customColors.primary,
    primaryDark: customColors.primaryDark,
    primaryLight: customColors.primaryLight,
    secondary: customColors.secondary,
    secondaryDark: customColors.secondaryDark,
    secondaryLight: customColors.secondaryLight,
    accent: customColors.accent,
    accentDark: customColors.accentDark,
    accentLight: customColors.accentLight,

    success: customColors.success,
    warning: customColors.warning,
    error: customColors.error,
    info: customColors.info,
  },

  space: { ...defaultConfig.tokens.space },
  size: { ...defaultConfig.tokens.size },
  radius: { ...defaultConfig.tokens.radius },
  zIndex: { ...defaultConfig.tokens.zIndex },
});

const config = createTamagui({
  ...defaultConfig,
  tokens: customTokens,
  fonts: {
    body: {
      family: 'System',
      size: {
        1: 12,
        2: 14,
        3: 16,
        4: 18,
        5: 20,
        6: 24,
        7: 28,
        8: 32,
        9: 36,
        10: 40,
        11: 44,
        12: 48,
        13: 52,
        14: 56,
        15: 60,
        16: 64,
        17: 68,
        18: 72,
        19: 76,
        20: 80,
      },
      lineHeight: {
        1: 16,
        2: 20,
        3: 24,
        4: 28,
        5: 32,
        6: 36,
        7: 40,
        8: 44,
        9: 48,
        10: 52,
        11: 56,
        12: 60,
        13: 64,
        14: 68,
        15: 72,
        16: 76,
        17: 80,
        18: 84,
        19: 88,
        20: 92,
      },
      weight: {
        1: '300',
        2: '400',
        3: '500',
        4: '600',
        5: '700',
        6: '800',
        7: '900',
      },
      letterSpacing: {
        1: 0,
        2: 0.5,
        3: 1,
        4: 1.5,
        5: 2,
        6: 2.5,
        7: 3,
        8: 3.5,
        9: 4,
        10: 4.5,
      },
    },
    heading: {
      family: 'System',
      size: {
        1: 12,
        2: 14,
        3: 16,
        4: 18,
        5: 20,
        6: 24,
        7: 28,
        8: 32,
        9: 36,
        10: 40,
        11: 44,
        12: 48,
        13: 52,
        14: 56,
        15: 60,
        16: 64,
        17: 68,
        18: 72,
        19: 76,
        20: 80,
      },
      lineHeight: {
        1: 16,
        2: 20,
        3: 24,
        4: 28,
        5: 32,
        6: 36,
        7: 40,
        8: 44,
        9: 48,
        10: 52,
        11: 56,
        12: 60,
        13: 64,
        14: 68,
        15: 72,
        16: 76,
        17: 80,
        18: 84,
        19: 88,
        20: 92,
      },
      weight: {
        1: '300',
        2: '400',
        3: '500',
        4: '600',
        5: '700',
        6: '800',
        7: '900',
      },
      letterSpacing: {
        1: 0,
        2: 0.5,
        3: 1,
        4: 1.5,
        5: 2,
        6: 2.5,
        7: 3,
        8: 3.5,
        9: 4,
        10: 4.5,
      },
    },
  },
  media: {
    ...defaultConfig.media,
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  },
  themes: {
    light: {
      primary: customColors.primary,
      primaryDark: customColors.primaryDark,
      secondary: customColors.secondary,
      success: customColors.success,
      warning: customColors.warning,
      error: customColors.error,
      info: customColors.info,
      background: customColors.light.bg,
      backgroundHover: customColors.light.cardHover,
      backgroundPress: customColors.light.borderHover,
      backgroundFocus: customColors.light.cardHover,
      backgroundStrong: customColors.light.card,
      color: customColors.light.text,
      colorHover: customColors.light.text,
      colorPress: customColors.light.text,
      colorFocus: customColors.light.text,
      colorSecondary: customColors.light.textSecondary,
      colorTertiary: customColors.light.textTertiary,
      borderColor: customColors.light.border,
      borderColorHover: customColors.light.borderHover,
      borderColorPress: customColors.light.borderHover,
      borderColorFocus: customColors.primary,
      outlineColor: customColors.primary,
      placeholderColor: customColors.light.textTertiary,
      shadowColor: 'rgba(0, 0, 0, 0.05)',
      shadowColorHover: 'rgba(0, 0, 0, 0.1)',
    },
    dark: {
      primary: customColors.primary,
      primaryDark: customColors.primaryDark,
      secondary: customColors.secondary,
      success: customColors.success,
      warning: customColors.warning,
      error: customColors.error,
      info: customColors.info,
      background: customColors.dark.bg,
      backgroundHover: customColors.dark.cardHover,
      backgroundPress: customColors.dark.border,
      backgroundFocus: customColors.dark.cardHover,
      backgroundStrong: customColors.dark.card,
      color: customColors.dark.text,
      colorHover: customColors.dark.text,
      colorPress: customColors.dark.text,
      colorFocus: customColors.dark.text,
      colorSecondary: customColors.dark.textSecondary,
      colorTertiary: customColors.dark.textTertiary,
      borderColor: customColors.dark.border,
      borderColorHover: customColors.dark.borderHover,
      borderColorPress: customColors.dark.borderHover,
      borderColorFocus: customColors.primary,
      outlineColor: customColors.primary,
      placeholderColor: customColors.dark.textTertiary,
      shadowColor: 'rgba(0, 0, 0, 0.2)',
      shadowColorHover: 'rgba(0, 0, 0, 0.3)',
    },
  },
});

export type Conf = typeof config;

declare module '@tamagui/core' {
  interface TamaguiCustomConfig extends Conf {}
}

export default config;
